[project]
name = "cvtest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "moviepy>=2.1.2",
    "opencv-contrib-python>=4.11.0.86",
    "opencv-python>=4.11.0.86",
]
